package gg.modl.backend.database.mongo.codegen;

import java.util.Set;
import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.annotation.processing.SupportedSourceVersion;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.ElementFilter;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@SupportedAnnotationTypes("gg.modl.backend.database.mongo.codegen.GenerateMongoFields")
@SupportedSourceVersion(SourceVersion.RELEASE_21)
public final class MongoFieldsProcessor extends AbstractProcessor {
    private static final String GENERATED_PACKAGE = "gg.modl.backend.database.mongo.fields";
    private static final String GENERATE_ANNOTATION = "gg.modl.backend.database.mongo.codegen.GenerateMongoFields";
    private static final String FIELD_ALIAS_ANNOTATION = "gg.modl.backend.database.mongo.codegen.MongoFieldAlias";
    private static final String FIELD_ALIASES_ANNOTATION = "gg.modl.backend.database.mongo.codegen.MongoFieldAliases";
    private static final String ID_ANNOTATION = "org.springframework.data.annotation.Id";
    private static final String FIELD_ANNOTATION = "org.springframework.data.mongodb.core.mapping.Field";
    private static final String MAP_TYPE = "java.util.Map";
    private static final String COLLECTION_TYPE = "java.util.Collection";

    private Types types;
    private Elements elements;
    private Messager messager;
    private Filer filer;

    @Override
    public synchronized void init(ProcessingEnvironment processingEnv) {
        super.init(processingEnv);

        this.types = processingEnv.getTypeUtils();
        this.elements = processingEnv.getElementUtils();
        this.messager = processingEnv.getMessager();
        this.filer = processingEnv.getFiler();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (final Element element : roundEnv.getElementsAnnotatedWith(getTypeElement(GENERATE_ANNOTATION))) {
            if (!(element instanceof TypeElement typeElement)) {
                error(element, "@GenerateMongoFields can only target classes");
                continue;
            }

            if (typeElement.getKind() != ElementKind.CLASS && typeElement.getKind() != ElementKind.RECORD) {
                error(typeElement, "@GenerateMongoFields can only target classes or records");
                continue;
            }

            generateFieldsClass(typeElement);
        }

        return true;
    }

    private void generateFieldsClass(TypeElement rootType) {
        final String generatedClassName = generatedClassName(rootType);
        final Map<String, String> constants = new LinkedHashMap<>();

        for (final VariableElement field : collectPersistentFields(rootType)) {
            addConstant(constants, toConstantName(field.getSimpleName().toString()), persistedFieldName(field), rootType);
        }

        for (final AliasDescriptor alias : aliasDescriptors(rootType)) {
            addConstant(constants, alias.name(), resolveAliasPath(rootType, alias.path()), rootType);
        }

        try {
            final JavaFileObject sourceFile = filer.createSourceFile(GENERATED_PACKAGE + "." + generatedClassName, rootType);
            try (final Writer writer = sourceFile.openWriter()) {
                writer.write("package " + GENERATED_PACKAGE + ";\n\n");
                writer.write("// Generated by MongoFieldsProcessor. Do not edit manually.\n");
                writer.write("public final class " + generatedClassName + " {\n");

                for (final Map.Entry<String, String> constant : constants.entrySet()) {
                    writer.write("    public static final String "
                            + constant.getKey() + " = \"" + escapeJava(constant.getValue()) + "\";\n");
                }

                writer.write("\n");
                writer.write("    private " + generatedClassName + "() {\n");
                writer.write("    }\n");
                writer.write("}\n");
            }
        } catch (IOException exception) {
            error(rootType, "Failed to generate %s: %s", generatedClassName, exception.getMessage());
        }
    }

    private String generatedClassName(TypeElement rootType) {
        final AnnotationMirror generateAnnotation = annotationMirror(rootType, GENERATE_ANNOTATION);
        final String configuredName = annotationStringValue(generateAnnotation, "className");

        if (configuredName != null && !configuredName.isBlank()) {
            return configuredName;
        }

        return rootType.getSimpleName() + "Fields";
    }

    private List<VariableElement> collectPersistentFields(TypeElement rootType) {
        final Map<String, VariableElement> fieldsByName = new LinkedHashMap<>();
        collectPersistentFields(rootType, fieldsByName);

        return new ArrayList<>(fieldsByName.values());
    }

    private void collectPersistentFields(TypeElement type, Map<String, VariableElement> fieldsByName) {
        final TypeMirror superclass = type.getSuperclass();
        if (superclass.getKind() == TypeKind.DECLARED) {
            final Element parentElement = types.asElement(superclass);
            if (parentElement instanceof TypeElement parentType && !parentType.getQualifiedName().contentEquals("java.lang.Object")) {
                collectPersistentFields(parentType, fieldsByName);
            }
        }

        for (final VariableElement field : ElementFilter.fieldsIn(type.getEnclosedElements())) {
            if (field.getModifiers().contains(Modifier.STATIC) || field.getModifiers().contains(Modifier.TRANSIENT)) {
                continue;
            }

            fieldsByName.putIfAbsent(field.getSimpleName().toString(), field);
        }
    }

    private List<AliasDescriptor> aliasDescriptors(TypeElement rootType) {
        final List<AliasDescriptor> aliases = new ArrayList<>();

        for (final AnnotationMirror annotationMirror : rootType.getAnnotationMirrors()) {
            final String annotationType = annotationType(annotationMirror);

            if (FIELD_ALIAS_ANNOTATION.equals(annotationType)) {
                aliases.add(new AliasDescriptor(
                        annotationStringValue(annotationMirror, "name"),
                        annotationStringValue(annotationMirror, "path")
                ));
                continue;
            }

            if (!FIELD_ALIASES_ANNOTATION.equals(annotationType)) {
                continue;
            }

            for (final AnnotationMirror nested : nestedAnnotations(annotationMirror, "value")) {
                aliases.add(new AliasDescriptor(
                        annotationStringValue(nested, "name"),
                        annotationStringValue(nested, "path")
                ));
            }
        }
        return aliases;
    }

    private List<AnnotationMirror> nestedAnnotations(AnnotationMirror annotationMirror, String propertyName) {
        final List<AnnotationMirror> nested = new ArrayList<>();
        for (final Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry : annotationMirror.getElementValues().entrySet()) {
            if (!propertyName.equals(entry.getKey().getSimpleName().toString())) {
                continue;
            }

            final Object value = entry.getValue().getValue();
            if (!(value instanceof List<?> values)) {
                continue;
            }

            for (Object nestedValue : values) {
                if (nestedValue instanceof AnnotationValue annotationValue && annotationValue.getValue() instanceof AnnotationMirror mirror) {
                    nested.add(mirror);
                }
            }
        }

        return nested;
    }

    private void addConstant(Map<String, String> constants, String name, String path, TypeElement rootType) {
        if (name == null || name.isBlank()) {
            error(rootType, "Generated Mongo field name must not be blank");
            return;
        }

        if (path == null || path.isBlank()) {
            error(rootType, "Generated Mongo path for %s must not be blank", name);
            return;
        }

        final String previous = constants.putIfAbsent(name, path);
        if (previous != null && !previous.equals(path)) {
            error(rootType, "Duplicate generated Mongo field constant %s on %s", name, rootType.getQualifiedName());
        }
    }

    private String resolveAliasPath(TypeElement rootType, String configuredPath) {
        final String[] segments = configuredPath.split("\\.");
        final StringBuilder builder = new StringBuilder();
        TypeMirror currentType = rootType.asType();

        for (final String segment : segments) {
            if (segment.isBlank()) {
                error(rootType, "Invalid empty segment in alias path %s", configuredPath);
                return configuredPath;
            }

            if (segment.equals("$") || segment.equals("$[]")) {
                appendSegment(builder, segment);
                continue;
            }

            if (currentType == null || currentType.getKind().isPrimitive() || isMapType(currentType)) {
                appendSegment(builder, segment);
                currentType = null;
                continue;
            }

            final VariableElement field = findField(currentType, segment);
            if (field == null) {
                error(rootType, "Unknown Mongo alias segment %s in path %s for %s", segment, configuredPath, rootType.getQualifiedName());
                return configuredPath;
            }

            appendSegment(builder, persistedFieldName(field));
            currentType = nestedType(field.asType());
        }

        return builder.toString();
    }

    private void appendSegment(StringBuilder builder, String segment) {
        if (!builder.isEmpty()) {
            builder.append('.');
        }

        builder.append(segment);
    }

    private VariableElement findField(TypeMirror typeMirror, String fieldName) {
        if (typeMirror.getKind() != TypeKind.DECLARED) {
            return null;
        }

        final Element element = types.asElement(typeMirror);
        if (!(element instanceof TypeElement typeElement)) {
            return null;
        }

        return findField(typeElement, fieldName);
    }

    private VariableElement findField(TypeElement typeElement, String fieldName) {
        TypeElement current = typeElement;

        while (current != null && !current.getQualifiedName().contentEquals("java.lang.Object")) {
            for (VariableElement field : ElementFilter.fieldsIn(current.getEnclosedElements())) {
                if (field.getSimpleName().contentEquals(fieldName)) {
                    return field;
                }
            }

            final TypeMirror superclass = current.getSuperclass();
            if (superclass.getKind() != TypeKind.DECLARED) {
                break;
            }

            current = (types.asElement(superclass) instanceof TypeElement parentType) ? parentType : null;
        }

        return null;
    }

    private TypeMirror nestedType(TypeMirror typeMirror) {
        if (typeMirror.getKind() == TypeKind.ARRAY) {
            return ((ArrayType) typeMirror).getComponentType();
        }

        if (!isDeclaredType(typeMirror)) {
            return typeMirror;
        }

        if (isMapType(typeMirror)) {
            return null;
        }

        if (!isCollectionType(typeMirror)) {
            return typeMirror;
        }

        final DeclaredType declaredType = (DeclaredType) typeMirror;
        if (declaredType.getTypeArguments().isEmpty()) {
            return null;
        }

        return declaredType.getTypeArguments().getFirst();
    }

    private boolean isDeclaredType(TypeMirror typeMirror) {
        return typeMirror.getKind() == TypeKind.DECLARED;
    }

    private boolean isMapType(TypeMirror typeMirror) {
        return isAssignableTo(typeMirror, MAP_TYPE);
    }

    private boolean isCollectionType(TypeMirror typeMirror) {
        return isAssignableTo(typeMirror, COLLECTION_TYPE);
    }

    private boolean isAssignableTo(TypeMirror sourceType, String targetTypeName) {
        final TypeElement targetType = elements.getTypeElement(targetTypeName);
        if (targetType == null || sourceType == null) {
            return false;
        }

        return types.isAssignable(types.erasure(sourceType), types.erasure(targetType.asType()));
    }

    private String persistedFieldName(VariableElement field) {
        if (annotationMirror(field, ID_ANNOTATION) != null) {
            return "_id";
        }

        final AnnotationMirror fieldAnnotation = annotationMirror(field, FIELD_ANNOTATION);
        if (fieldAnnotation != null) {
            final String name = annotationStringValue(fieldAnnotation, "name");
            if (name != null && !name.isBlank()) {
                return name;
            }

            final String value = annotationStringValue(fieldAnnotation, "value");
            if (value != null && !value.isBlank()) {
                return value;
            }
        }

        return field.getSimpleName().toString();
    }

    private AnnotationMirror annotationMirror(Element element, String annotationType) {
        for (final AnnotationMirror mirror : element.getAnnotationMirrors()) {
            if (annotationType.equals(annotationType(mirror))) {
                return mirror;
            }
        }

        return null;
    }

    private String annotationType(AnnotationMirror mirror) {
        return ((TypeElement) mirror.getAnnotationType().asElement()).getQualifiedName().toString();
    }

    private String annotationStringValue(AnnotationMirror mirror, String propertyName) {
        if (mirror == null) {
            return null;
        }

        for (final Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> entry :
            processingEnv.getElementUtils().getElementValuesWithDefaults(mirror).entrySet()) {

            if (propertyName.equals(entry.getKey().getSimpleName().toString())) {
                Object value = entry.getValue().getValue();
                return value == null ? null : value.toString();
            }
        }

        return null;
    }

    private TypeElement getTypeElement(String qualifiedName) {
        return elements.getTypeElement(qualifiedName);
    }

    private String toConstantName(String fieldName) {
        final StringBuilder builder = new StringBuilder(fieldName.length() + 8);
        for (int index = 0; index < fieldName.length(); index++) {
            final char current = fieldName.charAt(index);
            if (index > 0 && shouldInsertUnderscore(fieldName, index)) {
                builder.append('_');
            }

            builder.append(Character.toUpperCase(current));
        }

        return builder.toString();
    }

    private boolean shouldInsertUnderscore(String value, int index) {
        final char current = value.charAt(index);
        final char previous = value.charAt(index - 1);

        if (Character.isUpperCase(current)) {
            return Character.isLowerCase(previous)
                    || Character.isDigit(previous)
                    || (index + 1 < value.length() && Character.isLowerCase(value.charAt(index + 1)));
        }

        if (Character.isDigit(current)) {
            return !Character.isDigit(previous);
        }

        return false;
    }

    private String escapeJava(String value) {
        return value.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private void error(Element element, String message, Object... args) {
        messager.printMessage(Diagnostic.Kind.ERROR, String.format(message, args), element);
    }

    private record AliasDescriptor(String name, String path) {
    }
}
